# Generated by Django 5.0.7 on 2024-08-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://via.placeholder.com/150', max_length=500),
        ),
    ]
